---
- hosts: all
  gather_facts: no
  vars:
    DBname: "Ansible"
    DBUsername: "root"
    DBPassword: ""
    DBHost: "172.18.0.3"
    ansiblegroup: "[server]"
  tasks:
    - name: Get the hostname from MySQL
      local_action:
        module: community.mysql.mysql_query
        login_db: "{{DBname}}"
        query: SELECT (Hostname) FROM Ansible.F5Details;
        login_host: "{{DBHost}}"
        login_password: "{{DBPassword}}"
        login_user: "{{DBUsername}}"
      register: queryresults
      run_once: true
    - name: "Add inventory to in memory"
      local_action:
        module: lineinfile
        path: "{{ansible_inventory_sources[0]}}"
        insertafter: "{{ansiblegroup}}"
        line: "{{item.Hostname}}"
      with_items: "{{queryresults.query_result}}"
    - name: "flush new inventory"
      meta: refresh_inventory
    - pause:
        minutes: 1
    - name: 
      debug:
        msg: "{{inventory_hostname}}"
...