---
- hosts: localhost
  gather_facts: no
  vars:
    inventory: 
      - "neighbor EVPN_RR peer group neighbor eccN_RR peer group neighbor EVPN_RR password 7 6ujdhkhdsfhsdkf neighbor 10.0.0.0 peer group SPINES neighbor 10.0.0.0 password 7 dsfgjkfdgjklfdg neighbor 10.1.0.0 peer group SPINES1 neighbor 10.1.0.0 password 7 dsfgjkfsdfsfdg"
      - "neighbor EVPN_RR peer group neighbor EVPN_RR password 7 6ujdhkhdsfhsdkf neighbor 10.0.0.0 peer group SPINES neighbor 10.0.0.0 password 7 dsfgjkfdgjklfdg neighbor 10.1.0.0 peer group SPINES1 neighbor 10.1.0.0 password 7 dsfgjkfsdfsfdg"
    pattern: "/[a-zA-Z_a-zA-z]+/g"
  tasks:
     - include: regex.yml
       vars:
        host: "{{ item }}"
       with_items:
       - "{{inventory}}"

        - name: SCP_Copy
      main:
        dmf_hostname: localhost
        backup_hostname: localhost
        dmf_username: root
        dmf_password: "Pass!2211"
        backup_username: root
        backup_password: "Pass!2211"
        dmf_backup_filepath: "/root/anaconda-ks.cfg"
        backup_dest_filepath: "/var/test"
      no_log: yes
      register: results
      
...
