- hosts: localhost
  vars:
    mssql_login_user: "sa"
    mssql_login_password: "Pass!2211"
    mssql_host: "192.168.1.137"
    mssql_port: 1433
    mssql_dbname: "cvp"
    gitlab_url: "https://gitlab.com/"
    gitlab_projectid: 48425181
  tasks:
    - name: Get SQL Statement 
      community.general.mssql_script:
        login_user: "{{ mssql_login_user }}"
        login_password: "{{ mssql_login_password }}"
        login_host: "{{ mssql_host }}"
        login_port: "{{ mssql_port }}"
        db: "{{ mssql_dbname }}"
        script: "select (cvp_name) from cvp_inv group by cvp_name;"
      register: sqlresult 
    - name: Get the DeviceGroup
      set_fact:
        RAW_DEVICE_GRP: "{{ RAW_DEVICE_GRP | default([]) + [ ((item | split('.') | first)[-3:])+'-'+item] }}" 
      with_items: "{{ sqlresult.query_results.0.0 }}"
    - name: Remove Duplicates Device Groups
      remove_duplicate:
        payload: "{{ RAW_DEVICE_GRP }}"
      register: DEVICE_GRP
    - name: Get SQL Statement 
      community.general.mssql_script:
        login_user: "{{ mssql_login_user }}"
        login_password: "{{ mssql_login_password }}"
        login_host: "{{ mssql_host }}"
        login_port: "{{ mssql_port }}"
        db: "{{ mssql_dbname }}"
        script: "select [fqdn] from cvp_inv where cvp_name in {{ item | split('-') | last }};"
      register: sqlresult
      with_items: "{{ DEVICE_GRP.msg }}"
    - name: Generate Dynamic Inventory 
      dynamic_inv:
        payload: "{{sqlresult | to_json }}"
        chunk_len: 3
        gitlab_project_id: "{{gitlab_projectid}}"
        access_token: "glpat-6qpigg8iykn16GA2T3Hs"
        gitlab_url: "{{ gitlab_url }}"
      register: result
    - name: Write Inventory to file
      ansible.builtin.lineinfile:
        path: inventory.ini
        line: "{{ result.msg }}"
        state: present
        create: true
    - name: Write the Inventory File to Package Registry
      uri:
        url: "{{gitlab_url}}api/v4/projects/{{gitlab_projectid}}/packages/generic/AristaInventory/LATEST/inventory.ini"
        method: PUT
        src: 'inventory.ini'
        headers:
          PRIVATE-TOKEN: 'glpat-6qpigg8iykn16GA2T3Hs'
        status_code: 201
      register: result
